apiVersion: v1
kind: ConfigMap
metadata:
  name: guguhaus-frontend-config
  namespace: guguhaus
data:
  APP_ENVIRONMENT: "production"
  URL: "https://99haus.net"
  NOTION_URL: "https://button-reminder-1c5.notion.site"
  NOTION_HISTORY_ID: "1aec305ec493801a91d0c82adafc7a43"
  NOTION_ARTICLES_ID: "1aec305ec49380cab7cbe21be017fdb5"
  NOTION_WIP_ID: "1aec305ec4938096a537f91afd7dc5b8"
  NOTION_PARTICIPANTS_ID: "1aec305ec493804e8a8cd1b799f4bd68"
  NOTION_LIMITED_ID: "1d4c305ec49380e4b15ccaf403113bf9"
  NOTION_BANNER_ID: "1dac305ec4938014a0def98c16213764"
  PG_HOST: "guguhaus-postgres.guguhaus.svc.cluster.local"
  PG_DATABASE: "guguhaus"
  PG_PORT: "5432"
